/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/about/site': RouteRecordInfo<'/about/site', '/about/site', Record<never, never>, Record<never, never>>,
    '/anime/': RouteRecordInfo<'/anime/', '/anime', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/comment/': RouteRecordInfo<'/comment/', '/comment', Record<never, never>, Record<never, never>>,
    '/links/': RouteRecordInfo<'/links/', '/links', Record<never, never>, Record<never, never>>,
    '/page/[page]': RouteRecordInfo<'/page/[page]', '/page/:page', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/posts/ai_system/': RouteRecordInfo<'/posts/ai_system/', '/posts/ai_system', Record<never, never>, Record<never, never>>,
    '/posts/ai_system复习/': RouteRecordInfo<'/posts/ai_system复习/', '/posts/ai_system复习', Record<never, never>, Record<never, never>>,
    '/posts/AI概论/': RouteRecordInfo<'/posts/AI概论/', '/posts/AI概论', Record<never, never>, Record<never, never>>,
    '/posts/bomblab/': RouteRecordInfo<'/posts/bomblab/', '/posts/bomblab', Record<never, never>, Record<never, never>>,
    '/posts/daemon/': RouteRecordInfo<'/posts/daemon/', '/posts/daemon', Record<never, never>, Record<never, never>>,
    '/posts/Datalab/': RouteRecordInfo<'/posts/Datalab/', '/posts/Datalab', Record<never, never>, Record<never, never>>,
    '/posts/docker/': RouteRecordInfo<'/posts/docker/', '/posts/docker', Record<never, never>, Record<never, never>>,
    '/posts/Doxygen&commit/': RouteRecordInfo<'/posts/Doxygen&commit/', '/posts/Doxygen&commit', Record<never, never>, Record<never, never>>,
    '/posts/GitIntro/': RouteRecordInfo<'/posts/GitIntro/', '/posts/GitIntro', Record<never, never>, Record<never, never>>,
    '/posts/hello-valaxy': RouteRecordInfo<'/posts/hello-valaxy', '/posts/hello-valaxy', Record<never, never>, Record<never, never>>,
    '/posts/proxylab/': RouteRecordInfo<'/posts/proxylab/', '/posts/proxylab', Record<never, never>, Record<never, never>>,
    '/posts/Psychology/': RouteRecordInfo<'/posts/Psychology/', '/posts/Psychology', Record<never, never>, Record<never, never>>,
    '/posts/ssh&remotessh/': RouteRecordInfo<'/posts/ssh&remotessh/', '/posts/ssh&remotessh', Record<never, never>, Record<never, never>>,
    '/posts/VPN_tutorial/': RouteRecordInfo<'/posts/VPN_tutorial/', '/posts/VPN_tutorial', Record<never, never>, Record<never, never>>,
    '/posts/人工智慧与现代物理I/': RouteRecordInfo<'/posts/人工智慧与现代物理I/', '/posts/人工智慧与现代物理I', Record<never, never>, Record<never, never>>,
    '/posts/健康的斯多葛主义/': RouteRecordInfo<'/posts/健康的斯多葛主义/', '/posts/健康的斯多葛主义', Record<never, never>, Record<never, never>>,
    '/posts/奇怪小技巧/': RouteRecordInfo<'/posts/奇怪小技巧/', '/posts/奇怪小技巧', Record<never, never>, Record<never, never>>,
    '/posts/对象存储基础/': RouteRecordInfo<'/posts/对象存储基础/', '/posts/对象存储基础', Record<never, never>, Record<never, never>>,
    '/posts/我的2024总结/': RouteRecordInfo<'/posts/我的2024总结/', '/posts/我的2024总结', Record<never, never>, Record<never, never>>,
    '/posts/斯多葛的具身治疗/': RouteRecordInfo<'/posts/斯多葛的具身治疗/', '/posts/斯多葛的具身治疗', Record<never, never>, Record<never, never>>,
    '/posts/置身事内/': RouteRecordInfo<'/posts/置身事内/', '/posts/置身事内', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'pages/index.md': {
      routes: '/'
      views: never
    }
    'node_modules/.pnpm/valaxy@0.26.6_@babel+parser_292ca60473918aa050916881a2788bd5/node_modules/valaxy/client/pages/[...path].vue': {
      routes: '/[...path]'
      views: never
    }
    'pages/404.md': {
      routes: '/404'
      views: never
    }
    'pages/about/index.md': {
      routes: '/about/'
      views: never
    }
    'pages/about/site.md': {
      routes: '/about/site'
      views: never
    }
    'pages/anime/index.md': {
      routes: '/anime/'
      views: never
    }
    'pages/archives/index.md': {
      routes: '/archives/'
      views: never
    }
    'pages/categories/index.md': {
      routes: '/categories/'
      views: never
    }
    'pages/comment/index.md': {
      routes: '/comment/'
      views: never
    }
    'pages/links/index.md': {
      routes: '/links/'
      views: never
    }
    'node_modules/.pnpm/valaxy-theme-sakura@0.10.2__21a14fedfcc9ad529e804c46016eec05/node_modules/valaxy-theme-sakura/pages/page/[page].vue': {
      routes: '/page/[page]'
      views: never
    }
    'pages/posts/ai_system/index.md': {
      routes: '/posts/ai_system/'
      views: never
    }
    'pages/posts/ai_system复习/index.md': {
      routes: '/posts/ai_system复习/'
      views: never
    }
    'pages/posts/AI概论/index.md': {
      routes: '/posts/AI概论/'
      views: never
    }
    'pages/posts/bomblab/index.md': {
      routes: '/posts/bomblab/'
      views: never
    }
    'pages/posts/daemon/index.md': {
      routes: '/posts/daemon/'
      views: never
    }
    'pages/posts/Datalab/index.md': {
      routes: '/posts/Datalab/'
      views: never
    }
    'pages/posts/docker/index.md': {
      routes: '/posts/docker/'
      views: never
    }
    'pages/posts/Doxygen&commit/index.md': {
      routes: '/posts/Doxygen&commit/'
      views: never
    }
    'pages/posts/GitIntro/index.md': {
      routes: '/posts/GitIntro/'
      views: never
    }
    'pages/posts/hello-valaxy.md': {
      routes: '/posts/hello-valaxy'
      views: never
    }
    'pages/posts/proxylab/index.md': {
      routes: '/posts/proxylab/'
      views: never
    }
    'pages/posts/Psychology/index.md': {
      routes: '/posts/Psychology/'
      views: never
    }
    'pages/posts/ssh&remotessh/index.md': {
      routes: '/posts/ssh&remotessh/'
      views: never
    }
    'pages/posts/VPN_tutorial/index.md': {
      routes: '/posts/VPN_tutorial/'
      views: never
    }
    'pages/posts/人工智慧与现代物理I/index.md': {
      routes: '/posts/人工智慧与现代物理I/'
      views: never
    }
    'pages/posts/健康的斯多葛主义/index.md': {
      routes: '/posts/健康的斯多葛主义/'
      views: never
    }
    'pages/posts/奇怪小技巧/index.md': {
      routes: '/posts/奇怪小技巧/'
      views: never
    }
    'pages/posts/对象存储基础/index.md': {
      routes: '/posts/对象存储基础/'
      views: never
    }
    'pages/posts/我的2024总结/index.md': {
      routes: '/posts/我的2024总结/'
      views: never
    }
    'pages/posts/斯多葛的具身治疗/index.md': {
      routes: '/posts/斯多葛的具身治疗/'
      views: never
    }
    'pages/posts/置身事内/index.md': {
      routes: '/posts/置身事内/'
      views: never
    }
    'pages/tags/index.md': {
      routes: '/tags/'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
